---
Description: Automate provisioning of CodeBuild with CodePipeline, CodeCommit, and
  CodeDeploy. **WARNING** This template creates one or more Amazon EC2 instances.
  You will be billed for the AWS resources used if you create a stack from this template.
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EmailAddress:
    Description: Email Address for sending SNS notifications for CodeCommit
    Type: String

  RepositoryBranch:
    Description: The name of the branch for the CodeCommit repo
    Type: String
    Default: master
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Can contain only ASCII characters.

  RepositoryName:
    Description: The name of the codecommit and ecr repositories
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Dynamic Configuration
      Parameters:
      - RepositoryBranch
    ParameterLabels:
      RepositoryName:
        default: CodeCommit Repository Name
      RepositoryBranch:
        default: CodeCommit Repository Branch
Resources:

  Topic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref EmailAddress
        Protocol: email

  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryDescription: CodeCommit Repository
      # Code:
      #   S3: 
      #     Bucket: clouddog-solutions-us-east-1
      #     Key: codebuild/samples/php.zip
      Triggers:
      - Name: MasterTrigger
        CustomData: !Ref RepositoryName
        DestinationArn: !Ref Topic
        Events:
        - all

  EcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  EcrRepoName:
    Value: !Ref EcrRepo
    Description: ECR Repository name
    Export:
      Name: !Sub ${AWS::StackName}-EcrRepoName
  EcrRepoArn:
    Value: !GetAtt EcrRepo.Arn
    Description: ECR Repository Arn
    Export:
      Name: !Sub ${AWS::StackName}-EcrRepoArn

  Topic:
    Value: !Ref Topic
    Description: Topic Arn
    Export:
      Name: !Sub ${AWS::StackName}-Topic 

  CodeCommitURL:
    Value: !Sub https://console.aws.amazon.com/codecommit/home?region=${AWS::Region}#/repository/${RepositoryName}/browse/HEAD/--/
    Description: Git Repository URL

  CloneUrlSsh:
    Value: !Sub "git clone ${CodeCommitRepo.CloneUrlSsh}"
    Description: Git command for CodeCommit repository

