version: 0.2

cache:
  paths:
    - node_modules

phases:
  pre_build:
    commands:
      - echo Installing Dependencies
      - npm install

  build:
    commands:
      - npm run lint

artifacts:
  files:
    - "**/*.yml"
  name: templates
  discard-paths: no
  base-directory: src    

  secondary-artifacts:
    sample-php-basic:
      files:
        - "**/*.yml"
      name: sample-php-basic
      discard-paths: no
      base-directory: src/samples/php-basic