version: 0.2

cache:
  paths:
    - node_modules

phases:
  pre_build:
    commands:
      - echo Installing Dependencies
      - npm install

  build:
    commands:
      - npm run lint
      - cd src/samples/php-basic && zip -r ../php-basic.zip .
      
artifacts:
  files:
    - "**/*.yml"
    - "samples/*.zip"
  name: templates
  discard-paths: no
  base-directory: src