---
Description: Static Website Pipeline for Multi Account Deployments 
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DevDeploymentBucket:
    Description: The Bucket created in target development account
    Type: String
    Default: ''
    MinLength: '0'
    MaxLength: '200'
    ConstraintDescription: 'must be a valid host name, eg: app.dev.mywebsite.com'  

  PrdDeploymentBucket:
    Description: The Bucket created in target production account
    Type: String
    Default: ''
    MinLength: '0'
    MaxLength: '200'
    ConstraintDescription: 'must be a valid host name, eg: app.mywebsite.com'  

Conditions:
  HasDevelopment: !Not [ !Equals [ '', !Ref DevDeploymentBucket ] ]
  HasProduction: !Not [ !Equals [ '', !Ref PrdDeploymentBucket ] ]

Resources:
  code:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/clouddog-solutions-us-east-1/devops/code/template.yml
      TimeoutInMinutes: '60'
      Parameters:
        RepositoryName: !Ref AWS::StackName 

  development:
    Type: AWS::CloudFormation::Stack
    Condition: HasDevelopment
    Properties:
      TemplateURL: https://s3.amazonaws.com/clouddog-solutions-us-east-1/devops/pipeline/gatsby/standard-template.yml
      TimeoutInMinutes: '60'
      Parameters:
        RepositoryName: !Ref AWS::StackName     
        DeployBucket: !Ref DevDeploymentBucket 
        Environment: dev
        BranchName: development

  master:
    Type: AWS::CloudFormation::Stack
    Condition: HasProduction
    Properties:
      TemplateURL: https://s3.amazonaws.com/clouddog-solutions-us-east-1/devops/pipeline/gatsby/standard-template.yml
      TimeoutInMinutes: '60'
      Parameters:
        RepositoryName: !Ref AWS::StackName 
        DeployBucket: !Ref PrdDeploymentBucket
        Environment: prd
        BranchName: master
