version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    ports:
      - 8080:80
    networks:
      container-network:
        aliases:
          - web
          
networks:
  container-network: