---
Description: Automate provisioning of CodeBuild with CodePipeline, CodeCommit, and CodeDeploy. 
AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  HostedZoneId:
    Description: Required to register HostName automatically, otherwise must configure
      DNS in your current provider
    Type: AWS::Route53::HostedZone::Id

  WebsiteHostName:
    Type: String
    Default: ''
    MinLength: '0'
    MaxLength: '200'
    ConstraintDescription: 'must be a valid host name, eg: app.dev.mywebsite.com'  

  CertificateArn:
    Type: String
    Default: ""
    Description: "ACM Certificate Arn, eg: arn:aws:acm:${AWS::REGION}:${AWS::ACCOUNT}:certificate/9e50ea95-8325-41bf-b318-8ec0fbcc70bb"

Resources:
  code:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/clouddog-solutions-us-east-1/devops/code/template.yml
      TimeoutInMinutes: '60'
      Parameters:
        RepositoryName: !Ref AWS::StackName   

  master:
    Type: AWS::CloudFormation::Stack
    DependsOn: runtime
    Properties:
      TemplateURL: https://s3.amazonaws.com/clouddog-solutions-us-east-1/devops/pipeline/angular/standard-template.yml
      TimeoutInMinutes: '60'
      Parameters:
        RepositoryName: !Ref AWS::StackName     
        DeployBucket: !GetAtt runtime.Outputs.StaticBucketName
        Environment: prd
        BranchName: master

  runtime:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/clouddog-solutions-us-east-1/infra/static-website/angular/standard-template.yml
      TimeoutInMinutes: '90'
      Parameters:  
        HostedZoneId: !Ref HostedZoneId
        WebsiteHostName: !Ref WebsiteHostName
        CertificateArn: !Ref CertificateArn                      
